version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "chillwavdb"
      POSTGRES_USER: "chillwavuser"
      POSTGRES_PASSWORD: "pgpwd4chillwav"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"





